@echo off
REM Fertilizer Optimizer - Cloud Deployment Script
REM This script guides you through deploying to the cloud

echo ========================================
echo FERTILIZER OPTIMIZER - CLOUD DEPLOYMENT
echo ========================================
echo.
echo This script will help you deploy the application to the cloud
echo for mobile access.
echo.

echo Step 1: Check prerequisites
echo ---------------------------
where git >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: Git is not installed.
    echo Please install Git from: https://git-scm.com/download/win
    exit /b 1
)

where docker >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: Docker is not installed.
    echo Please install Docker Desktop from: https://www.docker.com/products/docker-desktop/
    exit /b 1
)

echo ✓ Git is installed
echo ✓ Docker is installed
echo.

echo Step 2: Create GitHub Repository
echo --------------------------------
echo.
echo You need to create a GitHub repository:
echo 1. Go to https://github.com/new
echo 2. Repository name: fertilizer-optimizer (or your preferred name)
echo 3. Description: "Fertilizer recommendation system with ML"
echo 4. Choose Public or Private
echo 5. DO NOT initialize with README, .gitignore, or license
echo 6. Click "Create repository"
echo.
set /p GITHUB_REPO_URL="Enter your GitHub repository URL (e.g., https://github.com/yourusername/fertilizer-optimizer): "

if "%GITHUB_REPO_URL%"=="" (
    echo ERROR: GitHub repository URL is required.
    exit /b 1
)

echo.
echo Step 3: Push code to GitHub
echo ---------------------------
echo Adding remote origin and pushing code...
git remote add origin "%GITHUB_REPO_URL%"
if %errorlevel% neq 0 (
    echo ERROR: Failed to add remote. The URL might be incorrect.
    echo Please check the URL and try again.
    exit /b 1
)

git branch -M main
git push -u origin main
if %errorlevel% neq 0 (
    echo ERROR: Failed to push to GitHub.
    echo You may need to set up GitHub authentication.
    echo.
    echo Manual push instructions:
    echo 1. git remote add origin %GITHUB_REPO_URL%
    echo 2. git branch -M main
    echo 3. git push -u origin main
    exit /b 1
)

echo ✓ Code pushed to GitHub successfully!
echo.

echo Step 4: Deploy to Railway.app (Backend + Database)
echo --------------------------------------------------
echo.
echo Now deploy to Railway.app:
echo 1. Go to https://railway.app
echo 2. Sign up/login with GitHub
echo 3. Click "New Project" -> "Deploy from GitHub repo"
echo 4. Select your "fertilizer-optimizer" repository
echo 5. Railway will automatically detect the Dockerfile and deploy
echo 6. Add a PostgreSQL database: "New" -> "Database" -> "PostgreSQL"
echo 7. Add environment variables (see .env.example)
echo.
echo Important environment variables for Railway:
echo - DATABASE_URL: (auto-generated by Railway)
echo - SECRET_KEY: generate a strong random string
echo - API_KEY: generate a random API key
echo - CORS_ORIGINS: https://your-frontend-domain.vercel.app
echo.
set /p RAILWAY_DEPLOYED="Have you deployed to Railway? (y/n): "
if /i "%RAILWAY_DEPLOYED%" neq "y" (
    echo Please deploy to Railway first, then run this script again.
    exit /b 0
)

echo.
echo Step 5: Get Railway backend URL
echo --------------------------------
echo After deployment, Railway will provide a URL like:
echo https://fertilizer-optimizer-production.up.railway.app
echo.
set /p BACKEND_URL="Enter your Railway backend URL: "

if "%BACKEND_URL%"=="" (
    echo WARNING: No backend URL provided. Using placeholder.
    set BACKEND_URL=https://fertilizer-optimizer-production.up.railway.app
)

echo.
echo Step 6: Deploy frontend to Vercel
echo ---------------------------------
echo.
echo Now deploy the frontend to Vercel:
echo 1. Go to https://vercel.com
echo 2. Sign up/login with GitHub
echo 3. Click "Add New" -> "Project"
echo 4. Import your "fertilizer-optimizer" repository
echo 5. Configure settings:
echo    - Framework: Vite
echo    - Root Directory: fert-frontend
echo    - Build Command: npm run build
echo    - Output Directory: dist
echo 6. Add environment variables:
echo    - VITE_API_URL: %BACKEND_URL%
echo    - VITE_API_KEY: (same as backend API_KEY)
echo 7. Click "Deploy"
echo.
set /p VERCEL_DEPLOYED="Have you deployed to Vercel? (y/n): "
if /i "%VERCEL_DEPLOYED%" neq "y" (
    echo Please deploy to Vercel first, then run this script again.
    exit /b 0
)

echo.
echo Step 7: Test deployed application
echo --------------------------------
echo.
echo Testing your deployed application...
echo 1. Backend health check: %BACKEND_URL%/
echo 2. Frontend URL: (provided by Vercel after deployment)
echo 3. Test prediction API: %BACKEND_URL%/predict
echo.
echo Mobile testing:
echo 1. Open frontend URL on your mobile phone
echo 2. Test form submission
echo 3. Verify PDF generation works
echo.

echo Step 8: Configure for production
echo --------------------------------
echo.
echo Final configuration steps:
echo 1. Update CORS_ORIGINS in Railway with your Vercel frontend URL
echo 2. Set up custom domain (optional)
echo 3. Configure SSL certificates (auto on Railway/Vercel)
echo 4. Set up monitoring (UptimeRobot, Sentry)
echo.

echo ========================================
echo DEPLOYMENT COMPLETE!
echo ========================================
echo.
echo Your fertilizer optimizer is now deployed and accessible from mobile!
echo.
echo Backend: %BACKEND_URL%
echo Frontend: (check Vercel dashboard)
echo.
echo Next steps:
echo 1. Share the frontend URL with users
echo 2. Monitor application performance
echo 3. Set up database backups
echo 4. Scale as needed
echo.
echo For detailed instructions, see DEPLOYMENT_GUIDE.md
echo.