"""add training_jobs table

Revision ID: 415bb77cc17f
Revises: 859b7ace032c
Create Date: 2026-04-23 21:09:09.132272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415bb77cc17f'
down_revision: Union[str, None] = '859b7ace032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get database connection to check existing tables
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create datasets table only if it doesn't exist
    if 'datasets' not in existing_tables:
        op.create_table('datasets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column('processed_path', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('filesize_bytes', sa.Integer(), nullable=False),
        sa.Column('row_count', sa.Integer(), nullable=True),
        sa.Column('column_count', sa.Integer(), nullable=True),
        sa.Column('processing_log', sa.Text(), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    
    # Create training_jobs table only if it doesn't exist
    if 'training_jobs' not in existing_tables:
        op.create_table('training_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('dataset_ids', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('triggered_by', sa.Integer(), nullable=True),
        sa.Column('log', sa.Text(), nullable=True),
        sa.Column('artifact_path', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_training_jobs_id'), 'training_jobs', ['id'], unique=False)
    
    # Create plot_weather table only if it doesn't exist
    if 'plot_weather' not in existing_tables:
        op.create_table('plot_weather',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plot_id', sa.Integer(), nullable=False),
        sa.Column('temp_avg_c', sa.Float(), nullable=True),
        sa.Column('rainfall_3d_mm', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True),
        sa.Column('wind_kph', sa.Float(), nullable=True),
        sa.Column('risk_summary', sa.JSON(), nullable=True),
        sa.Column('raw_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_plot_weather_id'), 'plot_weather', ['id'], unique=False)
        op.create_index(op.f('ix_plot_weather_plot_id'), 'plot_weather', ['plot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get database connection to check existing tables
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Drop plot_weather table and indexes if they exist
    if 'plot_weather' in existing_tables:
        # Check if indexes exist before dropping
        indexes = inspector.get_indexes('plot_weather')
        index_names = [idx['name'] for idx in indexes]
        
        if 'ix_plot_weather_plot_id' in index_names:
            op.drop_index(op.f('ix_plot_weather_plot_id'), table_name='plot_weather')
        if 'ix_plot_weather_id' in index_names:
            op.drop_index(op.f('ix_plot_weather_id'), table_name='plot_weather')
        op.drop_table('plot_weather')
    
    # Drop training_jobs table and indexes if they exist
    if 'training_jobs' in existing_tables:
        indexes = inspector.get_indexes('training_jobs')
        index_names = [idx['name'] for idx in indexes]
        
        if 'ix_training_jobs_id' in index_names:
            op.drop_index(op.f('ix_training_jobs_id'), table_name='training_jobs')
        op.drop_table('training_jobs')
    
    # Drop datasets table and indexes if they exist
    if 'datasets' in existing_tables:
        indexes = inspector.get_indexes('datasets')
        index_names = [idx['name'] for idx in indexes]
        
        if 'ix_datasets_id' in index_names:
            op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
        op.drop_table('datasets')
    # ### end Alembic commands ###
